.\"
.Dd August 17, 2000
.Dt MALINT 1
.Os
.Sh NAME
.Nm malint
.Nd validate MPEG audio streams
.Sh SYNOPSIS
.Nm
.Op Fl cCdDEfFgGhIpPtTV
.Op Fl N Ar MIN
.Op Ar file ...
.Sh DESCRIPTION
The
.Nm
utility parses and validates the MPEG audio streams named in the file
arguments (or standard input if none are given) and prints information
about the streams and any format violations it finds.

The output for each file is grouped under a line with that file's
name.  The diagnostic and informative messages are preceded with the
byte offset it pertains to.
.Pp
.Sy Options
For options that specify what test should be performed, a lower case
letter turns the test on, an upperr case letter turns it off.  For
long options, prepend 
.Ar no-
to turn it off.
.Pp
The options are as follows:
.Bl -tag -width "--no-tag-contents" -compact
.It Fl c
.It Fl -crc
Check CRC fields of the MPEG stream (default).
.It Fl C
.It Fl -no-crc
Don't check CRC fields of the MPEG stream.
.It Fl d
.It Fl -duration
Display duration of the stream (default).
.It Fl D
.It Fl -no-duration
Don't display duration of the stream.
.It Fl E
.It Fl -error
Only display error diagnostics: ignore some warnings and don't display
tags and duration of the stream.
.It Fl f
.It Fl -header-change
Display header field changes that occur in the stream (default).
.It Fl F
.It Fl -no-header-change
Don't display changes in frame header fields.
.It Fl g
.It Fl -gap
Check for unused bytes in bit reservoir (default).
.It Fl G
.It Fl -no-gap
Don't check for unused bytes in bit reservoir.
.It Fl h
.It Fl -help
Display help message.
.It Fl I
.It Fl -fast-info
Display only info (bit rate, length, tags at beginning and end), do
not parse whole file.
.It Fl N
.It Fl -resync-count
.Ar MIN
If the stream gets out of sync, require at least 
.Ar MIN
consecutive frames to accept resync.
.It Fl p
.It Fl -padding
Check for missing padding in last frame (default).
.It Fl P
.It Fl -no-padding
Don't check for missing padding in last frame.
.It Fl t
.It Fl -tag
Display ID3 tags.
.It Fl T
.It Fl -no-tag
Don't display ID3 tags.
.It Fl -tag-contents
Display contents of ID3 tags (default).
.It Fl -no-tag-contents
Do not display contents of ID3 tags.
.It Fl V
.It Fl -version
Display version information.
.El
.Pp
.Sy Error and warning messages
.Bl -diag
.It CRC error (calc:XXXX != file:YYYY)
The CRC calculated by malint for this frame (XXXX) differs from the
CRC stored in the stream (YYYY).
.It frame data overflows frame (M > N)
The length of data in this frame (M, calculated from side-info or
bit-alloc) is more than the frame can contain (N).
.It illegal header XXXXXXXX (AAAA)
A frame header was not found where expected, instead the four bytes
XXXXXXXX (in hex, AAAA in ASCII) were found.
.It bit reservoir spans across ID3 tag
Parts of the bit reservoir are located before an ID3 tag, whereas this
frame is located after it.  This is dubious at best, since many
players do not account for tags when finding the bit reservoir for a
frame.
.It main_data_begin overflows bit reservoir (N > R)
main_data_begin says this frame uses N bytes of the bit reservoir, but
the previous frame only left R bytes as bit reservoir.
.It gap in bit stream (N < R)
Only N of the R bytes in the bit reservoir are used.  This is not an
error, and some encoder limit the amount of bit reservoir they'll use
(e.g. to one frame), gaps if it becomes bigger.
.It skipping N bytes
N bytes were skipped during resynchronization.
.It skipping N bytes, reaching EOF
N bytes were skipped during resynchronization, thus reaching the end
of the stream.  Resynchronization failed.
.It no sync found in 64k, bailing out
no sync was found while scanning 64k bytes.  Resynchronization was
given up.
.It short [last] frame N of L bytes (D+P=M missing)
The [last] frame should be L bytes long, but was found to be only N
bytes long.  D bytes of frame data and P bytes of padding (giving M
bytes total) are missing.
.It padding missing from [last] frame (P bytes)
All P bytes of padding was found to be missing from the [last] frame.
This shouldn't cause problems if it is the last frame.
.It padding missing from [last] frame (M of P bytes)
M of P bytes padding were found to be missing from the [last] frame.
This shouldn't cause problems if it is the last frame.
.El
.Sy Info messages
.Bl -diag
.It MPEG V layer L ...
Tells the MPEG version, audio layer and other parameters contained in
the frame header.  This is also output if header parameters change
within the stream.
.It play time: HH:MM:SS (N frames)
Play time of this stream is HH:MM:SS, it contains N frames.  (The play
time calculation does not work if the sampling frequency is not
constant throughout the stream.)
.It play time: HH:MM:SS (according to vbr tag)
If using fast info mode, the number of frames is not counted.
According to the VBR tag, play time of this stream is HH:MM:SS.
.It play time: HH:MM:SS (aproximately)
If using fast info mode, the number of frames is not counted.  Based
on the assumption that bit rate and sampling frequency are constant
throughout the stream, the number of frames is approximated as
file-length/frame-length, giving a play time of HH:MM:SS.
.El
.Sh AUTHORS
Dieter Baron <dillo@giga.or.at>
.Sh BUGS
VBR only works if the VBR tag is at the beginning of the stream
(possibly after an ID3 tag) and spans to the end of the stream.

Large ID3v2 tags (>64k) or ID3v2 tags with unsynchronization are not
handled properly.

Layer 2 CRC calculation is not performed.

Validation of the huffman data in layer 3 streams is not performed.
